# Generated by Django 4.1.2 on 2022-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
