# Generated by Django 4.1.2 on 2022-11-02 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_alter_todoproject_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoproject',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contact'),
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='timeline',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
