# Generated by Django 4.1.2 on 2022-11-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_todoproject_contact_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoproject',
            old_name='contact',
            new_name='user',
        ),
    ]
