# Generated by Django 4.1.2 on 2022-11-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_todoproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoproject',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
